targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            thunder: lib/src/foundation/persistence/database/database.dart
          schema_dir: lib/src/foundation/persistence/database/schemas/
