name: thunder
description: An open-source cross-platform Lemmy client for iOS and Android built with Flutter
publish_to: none
version: 0.8.0-4+85

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  link_preview_generator:
    git:
      url: https://github.com/thunder-app/link_preview_generator.git
      ref: 77a00003216591c32194c2af3c4fc1cf64797e53
  markdown_editor:
    git:
      url: https://github.com/thunder-app/markdown-editor.git
      ref: 34db147d5964b2e84f5a7e8edff4a5ce6b649ec8
  xayn_readability:
    git:
      url: https://github.com/xaynetwork/xayn_readability
  l10n_esperanto:
    git:
      url: https://github.com/veloce/l10n_esperanto
      ref: 62d45c60f7840a4591318bb477172136c999f946
  android_intent_plus: ^6.0.0
  app_links: ^6.3.2
  auto_size_text: ^3.0.0
  back_button_interceptor: ^8.0.0
  background_fetch: ^1.2.1
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  connectivity_plus: ^7.0.0
  dart_ping: ^9.0.0
  dart_ping_ios: ^4.0.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  dynamic_color: ^1.6.5
  equatable: ^2.0.5
  expandable: ^5.0.1
  extended_image: ^10.0.1
  fading_edge_scrollview: ^4.1.1
  flex_color_scheme: ^8.1.1
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.3.0
  flutter_custom_tabs: ^2.0.0-beta.1
  flutter_displaymode: ^0.6.0
  flutter_file_dialog: ^3.0.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^19.2.1
  flutter_markdown: ^0.7.3+1
  flutter_native_splash: ^2.3.1
  flutter_sharing_intent: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_typeahead: ^5.2.0
  gal: ^2.2.0
  html: ^0.15.4
  html_unescape: ^2.0.0
  http: ^1.2.1
  image_picker: ^1.0.0
  intl: ^0.20.2
  jovial_svg: ^1.1.19
  markdown: ^7.2.2
  overlay_support: ^2.1.0
  path: ^1.8.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  screenshot: ^3.0.0
  share_plus: ^12.0.0
  shared_preferences: ^2.1.2
  smooth_highlight: ^0.1.1
  stream_transform: ^2.1.0
  super_sliver_list: ^0.4.1
  unifiedpush: ^6.0.2
  url_launcher: ^6.1.11
  # There is an intentional space between the packge name and colon below. Do not remove!
  version : ^3.0.2
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.2.2
  webview_flutter_android: ^4.1.0
  webview_flutter_wkwebview: ^3.5.0
  youtube_player_flutter: ^9.1.0
  youtube_player_iframe: ^5.2.0
  freezed_annotation: ^3.1.0
  freezed: ^3.2.2
  sqlite3_flutter_libs: ^0.5.39
  gif_view: ^1.0.3
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  drift_dev: ^2.28.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/logo_monochrome.png
    - assets/logo_android.png
    - assets/logo_android_background.png
    - assets/logo_android_monochrome.png
    - assets/ca/
  fonts:
    - family: Thunder
      fonts:
        - asset: fonts/Thunder.ttf

flutter_native_splash:
  image: assets/logo.png
  color: 212123
