name: thunder
description: An open-source cross-platform Lemmy client for iOS and Android built with Flutter
publish_to: none
version: 0.9.0-4+99

environment:
  sdk: ^3.13.2
  flutter: ">=3.47.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  markdown_editor:
    git:
      url: https://github.com/thunder-app/markdown-editor.git
      ref: 34db147d5964b2e84f5a7e8edff4a5ce6b649ec8
  image_dimension_parser:
    git:
      url: https://github.com/thunder-app/image-dimension-parser.git
      ref: d9bfec9dfe6a53b2d032129ce56311ec02796a29
  l10n_esperanto: ^3.0.0
  android_intent_plus: ^6.1.0
  app_links: ^7.2.1
  auto_size_text: ^3.0.0
  back_button_interceptor: ^8.0.4
  background_fetch: ^1.7.0
  bloc: ^9.2.1
  bloc_concurrency: ^0.3.0
  cached_network_image: ^4.0.0
  collection: ^1.19.1
  connectivity_plus: ^7.3.1
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  dynamic_color: ^1.9.0
  equatable: ^2.1.0
  expandable: ^5.0.1
  fading_edge_scrollview: ^4.1.1
  flex_color_scheme: ^8.4.0
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.2
  flutter_custom_tabs: ^2.6.0
  flutter_displaymode: ^0.7.0
  flutter_file_dialog: ^3.3.2
  keyboard_detection: ^0.8.1
  flutter_local_notifications: ^22.3.0
  flutter_markdown: ^0.7.7+1
  flutter_native_splash: ^2.4.8
  flutter_sharing_intent: ^2.0.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_typeahead: ^6.0.0
  gal: ^2.3.3
  html: ^0.15.7
  html_unescape: ^2.0.0
  http: ^1.6.0
  image_picker: ^1.2.3
  intl: ^0.20.3
  jovial_svg: ^1.1.30
  markdown: ^7.3.1
  overlay_support: ^2.1.0
  path: ^1.9.1
  path_provider: ^2.1.6
  permission_handler: ^12.0.3
  screenshot: ^3.0.0
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  smooth_highlight: ^0.1.2
  stream_transform: ^2.1.2
  super_sliver_list: ^0.4.1
  unifiedpush: ^6.2.0
  webcrypto: 0.6.0
  url_launcher: ^6.3.2
  # There is an intentional space between the packge name and colon below. Do not remove!
  version : ^3.0.2
  video_player: ^2.14.0
  video_player_android: 2.12.0
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.14.1
  webview_flutter_wkwebview: ^3.26.1
  youtube_player_flutter: ^10.0.1
  youtube_player_iframe: ^6.0.2
  freezed_annotation: ^3.1.0
  freezed: ^4.0.1
  image: ^4.9.2
  sqlite3: ^3.5.2
  flutter_avif: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  build_runner: ^2.16.0
  drift_dev: ^2.34.5
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5
  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.4.2+1
  bloc_lint: ^0.4.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/logo_monochrome.png
    - assets/logo_android.png
    - assets/logo_android_background.png
    - assets/logo_android_monochrome.png
    - assets/ca/
  fonts:
    - family: Thunder
      fonts:
        - asset: fonts/Thunder.ttf
  config:
    enable-swift-package-manager: true

flutter_native_splash:
  image: assets/logo.png
  color: 212123
