/// Flutter icons Thunder
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Thunder
///      fonts:
///       - asset: fonts/Thunder.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Thunder {
  Thunder._();

  static const _kFontFam = 'Thunder';
  static const String? _kFontPkg = null;

  static const IconData microphone_variant = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_crown = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
