import 'package:thunder/src/features/instance/domain/utils/instance_link_utils.dart';

/// A textual label associated with a Lemmy/PieFed user.
class UserLabel {
  /// The ID of the object in the database (should never need to be set explicitly).
  final String id;

  /// The username of the user being labeled (in the form user@instance.tld).
  /// Use [usernameFromParts] to consistently generate this.
  final String username;

  /// The label which is being applied to the user.
  final String label;

  const UserLabel({
    required this.id,
    required this.username,
    required this.label,
  });

  UserLabel copyWith({String? id}) => UserLabel(
        id: id ?? this.id,
        username: username,
        label: label,
      );

  /// Generates a username string that can be used to uniquely identify entries in the UserLabels table
  static String usernameFromParts(String username, String actorId) {
    return '$username@${fetchInstanceNameFromUrl(actorId)}';
  }

  /// Splits a username generated by [usernameFromParts] back into name and instance
  static ({String username, String instance}) partsFromUsername(String username) {
    return (username: username.split('@')[0], instance: username.split('@')[1]);
  }
}
