default_platform(:android)

platform :android do
  desc "Build app for distribution (GitHub)"
  lane :build do
    gradle(
      project_dir: "android",
      task: "assemble",
      flavor: "production",
      build_type: "Release",
    )
  end
end

platform :ios do
  desc "Build app for distribution (TestFlight)"
  lane :build do
    sh("sh ./../scripts/ios/fix-build-version.sh")
    build_app(  
      workspace: "ios/Runner.xcworkspace",
      scheme: "production",
      output_name: "thunder-v#{sh("sh ./../scripts/get-version.sh")}.ipa",
      output_directory: "release",
    )
  end
end
